# Generated by Django 4.2.26 on 2026-04-02 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='baby_profiles/')),
                ('min_heart_rate', models.IntegerField(default=60)),
                ('max_heart_rate', models.IntegerField(default=160)),
                ('min_oxygen_level', models.IntegerField(default=90)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('quality_score', models.IntegerField(default=100)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.baby')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('battery_level', models.IntegerField(default=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.baby')),
            ],
        ),
        migrations.CreateModel(
            name='HealthReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('oxygen_level', models.IntegerField(help_text='SpO2 percentage')),
                ('baby_temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('room_temperature', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('room_humidity', models.IntegerField(blank=True, null=True)),
                ('is_moving', models.BooleanField(default=False)),
                ('sleep_status', models.CharField(choices=[('AWAKE', 'Awake'), ('LIGHT', 'Light Sleep'), ('DEEP', 'Deep Sleep')], default='AWAKE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='app.baby')),
            ],
            options={
                'indexes': [models.Index(fields=['baby', '-timestamp'], name='app_healthr_baby_id_7aa32a_idx')],
            },
        ),
    ]
