# Generated by Django 5.2.8 on 2026-04-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailyuserstat'),
    ]

    operations = [
    ]
